package com.unswipe.android.domain.model

/**
 * Enhanced usage event with context awareness for intelligent analytics
 */
data class ContextualUsageEvent(
    val id: Long = 0,
    val packageName: String,
    val eventType: String,
    val timestamp: Long,
    val contextType: ContextType,
    val locationContext: LocationContext = LocationContext.UNKNOWN,
    val deviceState: DeviceState,
    val sessionDuration: Long = 0L, // Duration in milliseconds
    val additionalData: String? = null
)

/**
 * Usage patterns detected by analytics engine
 */
data class UsagePattern(
    val type: PatternType,
    val description: String,
    val apps: List<String> = emptyList(),
    val confidence: Double = 0.0,
    val suggestion: String,
    val detectedAt: Long = System.currentTimeMillis(),
    val isActive: Boolean = true
)

/**
 * Types of usage patterns that can be detected
 */
enum class PatternType {
    BINGE_USAGE,        // Long sessions (>30 minutes)
    STRESS_USAGE,       // Increased usage during stress periods
    PROCRASTINATION,    // Usage during work hours
    IMPULSE_USAGE,      // Frequent short sessions
    SLEEP_DISRUPTION,   // Usage close to bedtime
    WORK_DISTRACTION    // Excessive social media during work
}

/**
 * Contextual insights generated by the analytics engine
 */
data class ContextualInsight(
    val type: InsightType,
    val message: String,
    val suggestion: String,
    val severity: InsightSeverity,
    val shouldNotify: Boolean = false,
    val actionButton: String? = null,
    val contextualTip: String? = null,
    val alternativeActivity: String? = null,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Types of insights that can be generated
 */
enum class InsightType {
    WORK_DISTRACTION,
    WORK_INTERRUPTION,
    SLEEP_HYGIENE,
    BINGE_WARNING,
    STRESS_INDICATOR,
    PRODUCTIVITY_TIP,
    WELLNESS_REMINDER
}

/**
 * Severity levels for insights
 */
enum class InsightSeverity {
    LOW,    // Gentle suggestion
    MEDIUM, // Warning
    HIGH    // Strong intervention needed
}